from src.globals import GRID_DIMENSIONS

# helper file containing static grid data for drawing the world

world_coordinate_vectors = [
    [[0, 0, 0], [1, 0, 0]],  # body
    [[0, 0, 0], [0, 1, 0]],  # body
    [[0, 0, 0], [0, 0, 1]],  # body
    [[GRID_DIMENSIONS, 0, 0], [GRID_DIMENSIONS, 1, 0]],
    [[GRID_DIMENSIONS, 0, 0], [GRID_DIMENSIONS, 0, 1]],
    [[GRID_DIMENSIONS, 0, 0], [GRID_DIMENSIONS - 1, 0, 0]],
    [[GRID_DIMENSIONS, GRID_DIMENSIONS, 0], [GRID_DIMENSIONS, GRID_DIMENSIONS - 1, 0]],
    [[GRID_DIMENSIONS, GRID_DIMENSIONS, 0], [GRID_DIMENSIONS - 1, GRID_DIMENSIONS, 0]],
    [[GRID_DIMENSIONS, GRID_DIMENSIONS, 0], [GRID_DIMENSIONS, GRID_DIMENSIONS, 1]],
    [[0, GRID_DIMENSIONS, 0], [1, GRID_DIMENSIONS, 0]],
    [[0, GRID_DIMENSIONS, 0], [0, GRID_DIMENSIONS, 1]],
    [[0, GRID_DIMENSIONS, 0], [0, GRID_DIMENSIONS - 1, 0]],
    [[0, 0, GRID_DIMENSIONS], [1, 0, GRID_DIMENSIONS]],
    [[0, 0, GRID_DIMENSIONS], [0, 1, GRID_DIMENSIONS]],
    [[0, 0, GRID_DIMENSIONS], [0, 0, GRID_DIMENSIONS - 1]],
    [[0, GRID_DIMENSIONS, GRID_DIMENSIONS], [1, GRID_DIMENSIONS, GRID_DIMENSIONS]],
    [[0, GRID_DIMENSIONS, GRID_DIMENSIONS], [0, GRID_DIMENSIONS - 1, GRID_DIMENSIONS]],
    [[0, GRID_DIMENSIONS, GRID_DIMENSIONS], [0, GRID_DIMENSIONS, GRID_DIMENSIONS - 1]],
    [[GRID_DIMENSIONS, 0, GRID_DIMENSIONS], [GRID_DIMENSIONS, 1, GRID_DIMENSIONS]],
    [[GRID_DIMENSIONS, 0, GRID_DIMENSIONS], [GRID_DIMENSIONS - 1, 0, GRID_DIMENSIONS]],
    [[GRID_DIMENSIONS, 0, GRID_DIMENSIONS], [GRID_DIMENSIONS, 0, GRID_DIMENSIONS - 1]],
    [
        [GRID_DIMENSIONS, GRID_DIMENSIONS, GRID_DIMENSIONS],
        [GRID_DIMENSIONS, GRID_DIMENSIONS, GRID_DIMENSIONS - 1],
    ],
    [
        [GRID_DIMENSIONS, GRID_DIMENSIONS, GRID_DIMENSIONS],
        [GRID_DIMENSIONS, GRID_DIMENSIONS - 1, GRID_DIMENSIONS],
    ],
    [
        [GRID_DIMENSIONS, GRID_DIMENSIONS, GRID_DIMENSIONS],
        [GRID_DIMENSIONS - 1, GRID_DIMENSIONS, GRID_DIMENSIONS],
    ],
]
